spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staralba?serverTimezone=UTC&characterEncoding=UTF-8
    username: staralba
    password: chocotree1234!

    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false
      show-sql: true
      properties:
        hibernate.enable_lazy_load_no_trans: true
        hibernate.format_sql: true

      http:
        encoding:
          charset: UTF-8
          enabled: true
          force: true